ExpansionManager:
    Enable: true
    Setting:
        IPAuth:
            Enable: true
            MaxAccounts: 3
        KeepInventory:
            Enable: true
            DropPercent: 20
        Protection:
            Enable: true
            WorldName:
             - 'world'
             - 'world_nether'
             - 'world_the_end'
            BlockIgniteByLightning: 1,0,0
            EntityBreakDoor: 2,0,0
            EntityChangeBlockByEnderman: 2,0,0
            EntityChangeBlockByWither: 2,0,0
            EntityDamage: 2,0,0
            EntityDamageByPetWhenOwnerOffline: 1,1,1
            EntityExplodeByCreeper: 1,1,1
            EntityExplodeByFireball: 1,0,0
            EntityExplodeByTNT: 1,1,1
            EntityExplodeByWitherSpawn: 1,0,0
            EntityExplodeByWitherSkull: 1,0,0
            HangingBreak: 2,0,0
            HangingPlace: 2,0,0
            PigZap: 2,0,0
            PlayerInteractTrampleSoil: 1,0,0
            PlayerInteractBreakBlock: 2,0,0
            PlayerInteractBreakBlockIDList:
             - '23,26,54,58,61,62,116,117,118,138,145'
             - ''
             - ''
    Message:
        AnotherIPIsUsing:
         'IP 與註冊資料不符'
        AccountsTooMuch:
         'IP 註冊的帳號超額'
        DropBroadcast:
         '§5[系統公告] §f%Player §d在死亡時不幸地將身上物品灑落一地。'
CommandManager:
    Enable: true
    Setting:
        CommandRestrict:
            Enable: true
            Allow:
             - 'back'
             - 'hat'
             - 'help'
             - 'home'
             - 'homeset'
             - 'money'
             - 'ping'
             - 'tip'
             - 'trade'
             - 'sell'
             - 'spawn'
        CommandCooldown:
            Enable: true
            List:
             - 'back:60'
             - 'home:60'
             - 'homeset:300'
             - 'spawn:60'
            Format: 秒鐘,分鐘,小時
        Back:
            Enable: true
            SpendFood: 2
            TipMessage:
             '§2[遊戲提示] §a輸入 §f/back §a可返回死亡點。'
        Hat:
            Enable: true
        Home:
            Enable: true
            SpendFood: 2
        Ping:
            Enable: true
            Value: 100,300
            Color: §a,§6,§c
        Spawn:
            Enable: true
            SpendFood: 2
            FirstJoinInSpawn: true
            FirstJoinStrikeLighting: true
    Message:
        ErrorCommandCooldown:
         '§4[系統提示] §c再次使用此指令尚需等待 §f%Time §c%Format。'
        ErrorFoodNotEnough:
         '§4[系統提示] §c飽食度不足此指令須消耗的量。'
        BackSuccess:
         '§6[系統訊息] §e已傳送回死亡點。'
        BackError:
         '§4[系統提示] §c沒有死亡點可返回。'
        HatSuccess:
         '§6[系統訊息] §e物品已成功放置到頭上。'
        HatErrorAir:
         '§4[系統提示] §c手上沒有物品可放置到頭上。'
        HatErrorPlural:
         '§4[系統提示] §c堆疊的物品無法放置到頭上。'
        HomeSucces:
         '§6[系統訊息] §e已傳送回家。'
        HomeError:
         '§4[系統提示] §c尚未設定家的位置。'
        HomesetSucces:
         '§6[系統訊息] §e已設定當前位置為家。'
        Ping:
         '§6[系統訊息] §e延遲時間為 %Ping §e毫秒。'
        SpawnSucces:
         '§6[系統訊息] §e已傳送回重生點。'
        SpawnsetSucces:
         '§6[系統訊息] §e重生點已設置完成。'
MessageManager:
    Enable: true
    Setting:
        Death: true
        Help: true
        Tip:
            Enable: true
            Interval: 1200
            Random: false
    Message:
        Chat:
         '§7[玩家訊息] §f%Player : %Message'
        Join:
         '§5[系統公告] §f%Player §d回到了這個世界。'
        Quit:
         '§5[系統公告] §f%Player §d離開了這個世界。'
        First:
         '§5[系統公告] §d新玩家 §f%Player §d誕生了。'
        Respawn:
         '§5[系統公告] §f%Player §d已獲得重生。'
        Death:
            Default:
                - '§5[系統公告] §f%Player §d死亡了。'
            Arrow:
                - '§5[系統公告] §f%Player §d被射殺了。'
            Contact:
                - '§5[系統公告] §f%Player §d被仙人掌戳死了。'
            Drowing:
                - '§5[系統公告] §f%Player §d溺死了。'
            Explosion:
                - '§5[系統公告] §f%Player §d被炸飛了。'
            Fall:
                - '§5[系統公告] §f%Player §d以為能安然無恙的著地。'
            FallingBlock:
                - '§5[系統公告] §f%Player §d被墜落的方塊壓死了。'
            Fire:
                - '§5[系統公告] §f%Player §d在火焰中昇天。'
                - '§5[系統公告] §f%Player §d被燒死了。'
            Fireball:
                - '§5[系統公告] §f%Player §d被火焰球砸死了。'
            Lava:
                - '§5[系統公告] §f%Player §d在岩漿裡溺斃。'
            Magic:
                - '§5[系統公告] §f%Player §d被魔法的力量給殺死。'
            Suffocation:
                - '§5[系統公告] §f%Player §d在牆壁裡窒息。'
            Suicide:
                - '§5[系統公告] §f%Player §d自殺了。'
            Strvation:
                - '§5[系統公告] §f%Player §d餓死了。'
            Void:
                - '§5[系統公告] §f%Player §d掉到世界外面了。'
            Wither:
                - '§5[系統公告] §f%Player §d凋零了。'
            PVP:
                - '§5[系統公告] §f%Player §d被 §f%Attacker §d置於死地。'
                - '§5[系統公告] §f%Player §d被 §f%Attacker §d活活揍死。'
            PVPArrow:
                - '§5[系統公告] §f%Player §d被 §f%Attacker §d射殺了。'
            CraftBlaze:
                - '§5[系統公告] §f%Player §d被 §f烈焰使者 §d殺死了。'
            CraftCaveSpider:
                - '§5[系統公告] §f%Player §d被 §f洞穴蜘蛛 §d殺死了。'
            CraftChargedCreeper:
                - '§5[系統公告] §f%Player §d被 §f高壓苦力怕 §d殺死了。'
            CraftCreeper:
                - '§5[系統公告] §f%Player §d被 §f苦力怕 §d殺死了。'
            CraftEnderDragon:
                - '§5[系統公告] §f%Player §d被 §f終界龍 §d殺死了。'
            CraftEnderman:
                - '§5[系統公告] §f%Player §d被 §f終界使者 §d殺死了。'
            CraftGhast:
                - '§5[系統公告] §f%Player §d被 §f地獄幽靈 §d殺死了。'
            CraftMagmaCube:
                - '§5[系統公告] §f%Player §d被 §f熔岩史萊姆 §d殺死了。'
            CraftPigZombie:
                - '§5[系統公告] §f%Player §d被 §f殭屍豬人 §d殺死了。'
            CraftSilverfish:
                - '§5[系統公告] §f%Player §d被 §f蠹魚 §d殺死了。'
            CraftSkeleton:
                - '§5[系統公告] §f%Player §d被 §f骷髏 §d殺死了。'
            CraftSkeletonArrow:
                - '§5[系統公告] §f%Player §d被 §f骷髏 §d射殺了。'
            CraftSlime:
                - '§5[系統公告] §f%Player §d被 §f史萊姆 §d殺死了。'
            CraftSpider:
                - '§5[系統公告] §f%Player §d被 §f蜘蛛 §d殺死了。'
            CraftWitch:
                - '§5[系統公告] §f%Player §d被 §f巫婆 §d殺死了。'
            CraftWither:
                - '§5[系統公告] §f%Player §d被 §f凋零怪 §d殺死了。'
            CraftWitherSkeleton:
                - '§5[系統公告] §f%Player §d被 §f凋零骷髏 §d殺死了。'
            CraftWolf:
                - '§5[系統公告] §f%Player §d被 §f狼 §d咬死了。'
            CraftWolfIsTamed:
                - '§5[系統公告] §f%Player §d被 §f%Attacker §d的狼殺死了。'
            CraftZombie:
                - '§5[系統公告] §f%Player §d被 §f僵屍 §d殺死了。'
        Help:
            Player:
                - '§3[系統幫助] §b傳送到前個死亡處 §9/back'
                - '§3[系統幫助] §b將物品放置到頭上 §9/hat'
                - '§3[系統幫助] §b傳送到所設定的家 §9/home'
                - '§3[系統幫助] §b設置當前位置為家 §9/homeset'
                - '§3[系統幫助] §b查詢擁有的金錢量 §9/money'
                - '§3[系統幫助] §b檢查當前延遲時間 §9/ping'
                - '§3[系統幫助] §b切換遊戲提示顯示 §9/tip'
                - '§3[系統幫助] §b回應交易同意與否 §9/trade'
                - '§3[系統幫助] §b以手中物品來交易 §9/sell'
                - '§3[系統幫助] §b傳送到地圖重生點 §9/spawn'
            Operator:
                - '§3[系統幫助] §b設置玩家的金錢量 §9/moneyset §c[Operator]'
                - '§3[系統幫助] §b設置為地圖重生點 §9/spawnset §c[Operator]'
        Tip:
            Open:
             '§6[系統訊息] §e已開啟遊戲提示。'
            Close:
             '§6[系統訊息] §e已關閉遊戲提示。'
            Tips:
                - '§2[遊戲提示] §a使用傳送類指令需要消耗飽食度。'
                - '§2[遊戲提示] §a死亡時將有機率掉落身上物品。'
                - '§2[遊戲提示] §a當所有線上玩家都使用床時將可跳過夜晚。'
                - '§2[遊戲提示] §a當身上物品欄已滿時系統給予的物品將會掉落至地上。'
BonusSystem:
    Enable: true
    Setting:
        TimerInterval: 60
        BonusInterval: 1800
    Group:
        0:
            Item:
                - 50x3
                - 260x5
            Percent: 100
            Message:
             '§6[系統訊息] §e獲得補給 : %Item1 §fx3§e 、%Item2 §fx5 §e。'
        1:
            Item:
                - 297x5
            Percent: 100
            Message:
             '§6[系統訊息] §e獲得補給 : %Item1 §fx5 §e。'
        2:
            Item:
                - 388x10
            Percent: 10
            Message:
             '§6[系統訊息] §e獲得補給 : %Item1 §fx10 §e。'
            Broadcast: true
            BroadcastMessage:
             '§5[系統公告] §f%Player §d幸運地獲得稀有補給 §f10 §d個%Item1。'
MoneySystem:
    Enable: true
    Setting:
        Blaze: '300,200,90'
        CaveSpider: '140,70,80'
        ChargedCreeper: '300,150,75'
        Creeper: '150,75,75'
        EnderDragon: '20000,10000,100'
        Enderman: '400,100,90'
        Ghast: '500,300,90'
        MagmaCube: '75,45,75'
        PigZombie: '250,150,95'
        Silverfish: '20,10,50'
        Skeleton: '120,80,90'
        Slime: '30,15,75'
        Spider: '80,40,80'
        Wither: '5000,2500,100'
        WitherSkeleton: '270,190,90'
        Witch: '200,100,90'
        Zombie: '90,70,95'
        TradeTime: 60
    Message:
        GetMoney:
         '§6[系統訊息] §e狩獵 §f%Monster §e獲得賞金 §f%Drop §e金幣。'
        CheckMoney:
         '§6[系統訊息] §e目前擁有 §f%Money §e金幣。'
        EnderDragonDeath:
         '§5[系統公告] §f%Monster §d被擊敗了！ 所有玩家獲得 §f%Drop §d金幣。'
        EnderDragonDeathByHero:
         '§5[系統公告] §f%Hero §d給予 §f%Monster §d最後一擊！ 所有玩家獲得 §f%Drop §d金幣。'
        SuccessSet:
         '§6[系統訊息] §e已將 §f%Player §e的持有金設為 §f%Money §e金幣。'
        SuccessSetAdd:
         '§6[系統訊息] §e已將 §f%Player §e的持有金增加 §f%Amount §e為 §f%Money §e金幣。'
        SuccessSetSubtract:
         '§6[系統訊息] §e已將 §f%Player §e的持有金減少 §f%Amount §e為 §f%Money §e金幣。'
        ErrorData:
         '§4[系統提示] §c該玩家名稱不存在。'
        ErrorFormat:
         '§4[系統提示] §c正確格式為 /moneyset <玩家名稱> <增減數量>'
        ErrorFormatTrade:
         '§4[系統提示] §c正確格式為 /trade yes 或者 /trade no'
        ErrorFormatSell:
         '§4[系統提示] §c正確格式為 /sell <玩家名稱> <販售金額>'
        ErrorOfflineSell:
         '§4[系統提示] §c該玩家不在線上。'
        ErrorPriceSell:
         '§4[系統提示] §c交易金額不正確。'
        ErrorSelfSell:
         '§4[系統提示] §c無法與自己交易。'
        ErrorIngSell:
         '§4[系統提示] §c你正在交易當中。'
        ErrorItemSell:
         '§4[系統提示] §c手中無交易物品。'
        SellRequesting:
         '§6[系統訊息] §e已向對方提出交易。請靜候對方回應…'
        SellRequestError:
         '§4[系統提示] §c對方正在與他人交易。'
        TradeErrorRequesting:
         '§4[系統提示] §c你正在等候交易回應。'
        TradeErrorNoRequest:
         '§4[系統提示] §c你沒有交易需要回應。'
        TradeSuccessBuyer: |
         §6[系統訊息] §e交易成功。
         §6[系統訊息] §e已獲得交易物品並支付給 §f%Player §e共 §f%Price §e金幣。
        TradeSuccessSeller: |
         §6[系統訊息] §e交易成功。
         §6[系統訊息] §e§f%Player §e已支付給你 §f%Price §e金幣。
        TradeFailNoMoneyBuyer:
         '§4[系統提示] §c交易失敗。你沒有足夠的金錢購買。'
        TradeFailNoMoneySeller:
         '§4[系統提示] §c交易取消。對方沒有足夠的金錢購買。'
        TradeFailBuyer:
         '§6[系統訊息] §e已拒絕對方此交易。'
        TradeFailSeller:
         '§4[系統提示] §c交易失敗。對方拒絕此交易。'
        TradeFailOffline:
         '§4[系統提示] §c交易取消。對方不在線上。'
        TradeFailTimeout:
         '§4[系統提示] §c交易已逾時。'
        TradeTemp:
         '§4[系統提示] §c你有一個交易物品已回收。'
        TradeRequest:
         '§6[系統訊息] §e§f%Player §e向你販售 §f%Item%InfoDurability%InfoEnchantments §e數量 §f%Amount §e共 §f%Price §e金幣。'
        TradeRequestTip:
         '§2[遊戲提示] §a請輸入 §f/trade <yes/no> §a來回應此交易。'
        TradeInfoDurability:
         ' §e損耗 §f%Durability'
        TradeInfoEnchantments:
         ' §e附魔 §f%Enchantments'